### ISSUE TITLE
How to obtain the original unaggregated cxg dataset

### ISSUE THREAD

**Issue by mrbeann** [emdann/sc_target_evidence#14]
Thanks for this amazing work. I was wondering how can I get the original cxg dataset. I try to use the "sc_target_evidence/src/process_sc_data.py", but it seems "TargetDiseasePairs_OpenTargets_cellXgeneID_12072023.csv" is missing.

**Comment by emdann** [comment]
Hi @mrbeann, thanks for pointing this out! In practice you only need that file if you set `--keep_all_genes` to False in the script parameters (which we never did in the final analysis). That table contains the list of gene-disease pairs included in Open Targets, which are included in the [results table](https://github.com/emdann/sc_target_evidence/blob/master/data/suppl_table_disease_target_evidence.csv). 

I will amend the scripts to avoid future confusion during revision.

**Comment by mrbeann** [comment]
Thank you for your reply. But the format in "suppl_table_disease_target_evidence.csv" seems different from  "TargetDiseasePairs_OpenTargets_cellXgeneID_12072023.csv", and this file will read even if --keep_all_genes to True. 
I guess you mean we can skip Line 61 "all_genes_ls.extend(target_genes)"?
